### ISSUE TITLE
Error on running nyancat

### ISSUE THREAD

**Issue by leonardo-nicolas** [nickvdyck/nyancat.cs#11]
When I run nyancat command, after install using "`dotnet tool install --global nyancat --version 1.5.0`", as I got on NuGet.org, from ".NET CLI (Global)" tab, I got an error described bellow:
```terminal
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/home/leonardo/.dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=fedora.35-x64
```
I'm a Fedora 35 user and I installed manually DotNet 6 from microsoft binaries.

**Comment by vandycknick** [comment]
Thanks for bringing this to my attention, this is mainly because I haven't taken the time yet to upgrade to dotnet 6: https://github.com/nickvdyck/nyancat.cs/blob/ee24c8cda0c754693f31889d31f16511f5f4d992/Nyancat/Nyancat.csproj#L5. I'll need to add the net6.0 target framework in order for it to work on the latest dotnet. 

I should probably also add this to my csproj, it allows an executable to automatically roll forward when new major versions are released:
```xml
<PropertyGroup>
  <RollForward>Major</RollForward>
</PropertyGroup>
```

For now, you can get it working by running it like this:

```sh
DOTNET_ROLL_FORWARD=Major nyancat
```
This way you are forcing dotnet to roll forward to the latest major version: https://docs.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior

Feel free to submit a PR! 😄

**Comment by leonardo-nicolas** [comment]
Hi!
Thanks! I'll try again to change it, as soon as when I got time for this.

I preferred to open this issue, because I didn't know if you would think it was good or bad and I was afraid of your reaction, on opening Pull Requests.
Because there are programmers that they prefer to modify its codes by itself, and they refuse Pull Requests and, sometimes, they even block that dev who opened the Pull Request...

Apparently, you don't care who opens Pull Requests... Thanks for letting me contribute, and I will, as soon as I have some free time!😄😄😄😄😄😄😄😄
